export const QUESTIONS = [
  'Trái táo màu gì?',
  'Quả gì cay?',
  'Bà Phón có bao nhiêu đứa con?',
  'Phón Dậu 1 ở quận nào?',
  'Tại sao tên là Phón Dậu?',
  'Tập đoàn Phón Dậu bây giờ có mấy chi nhánh?',
  'Trong Phủng ché, Chị Xuân, Xây Dìa, Chị Thảo thì ai là người vào làm cho Bà Phón sớm nhất?',
  'Chi nhánh nào có nhiều máy lạnh nhất?',
  'Ai là người nấu ăn tối cho nhân viên?',
  'Phón Dậu đã được thành lập bao nhiêu năm?',
  'Tên giấy tờ của Bà Phón là gì?',
  'Bà Phón tuổi con gì?',
  'Bà Dậu là má của thằng nào?',
  'Tuấn Nguyên là một người ông chủ như thế nào?',
  'Kết Thúc trò chơi!',
];
export const ANSWERS = [
  [
    {value:'Đỏ', isCorrect: true},
    {value:'Trắng', isCorrect: false},
    {value:'Tím', isCorrect: false},
    {value:'Đen', isCorrect: false},
  ],
  [
    {value:'Cà rốt', isCorrect: false},
    {value:'Chuối', isCorrect: false},
    {value:'Ớt', isCorrect: true},
    {value:'Táo', isCorrect: false},
  ],
  [
    {value:'1', isCorrect: false},
    {value:'2', isCorrect: true},
    {value:'3', isCorrect: false},
    {value:'4', isCorrect: false},
  ],
  [
    {value:'1', isCorrect: false},
    {value:'3', isCorrect: false},
    {value:'5', isCorrect: false},
    {value:'6', isCorrect: true},
  ],
  [
    {value:'Chủ là Phón với Dậu', isCorrect: true},
    {value:'Bà Phón lớn hơn Bà Dậu', isCorrect: false},
    {value:'Bà Phón thích như vậy', isCorrect: false},
    {value:'Bà Dậu thích như vậy', isCorrect: false},
  ],
  [
    {value:'2', isCorrect: false},
    {value:'3', isCorrect: false},
    {value:'4', isCorrect: true},
    {value:'10!', isCorrect: false},
  ],
  [
    {value:'Phủng ché', isCorrect: false},
    {value:'Chị Xuân', isCorrect: true},
    {value:'Xây Dìa', isCorrect: false},
    {value:'Chị Thảo', isCorrect: false},
  ],
  [
    {value:'Bình Tiên', isCorrect: false},
    {value:'629', isCorrect: true},
    {value:'299', isCorrect: false},
    {value:'Halo', isCorrect: false},
  ],
  [
    {value:'Phì Día', isCorrect: false},
    {value:'Dì Linh', isCorrect: false},
    {value:'Bà Phón', isCorrect: false},
    {value:'Chị Ly', isCorrect: true},
  ],
  [
    {value:'10', isCorrect: false},
    {value:'13', isCorrect: false},
    {value:'15', isCorrect: true},
    {value:'18', isCorrect: false},
  ],
  [
    {value:'Tăng Muổi', isCorrect: false},
    {value:'Tăng Tiểu Phương', isCorrect: false},
    {value:'Tăng Anh', isCorrect: true},
    {value:'Đường Tăng', isCorrect: false},
  ],
  [
    {value:'Con Heo', isCorrect: false},
    {value:'Con Khỉ', isCorrect: false},
    {value:'Con Rồng', isCorrect: false},
    {value:'Con Hổ', isCorrect: true},
  ],
  [
    {value:'Hào Mập', isCorrect: false},
    {value:'Nguyên Tài Lanh', isCorrect: false},
    {value:'A Dương', isCorrect: true},
    {value:'Đạt Ruồi', isCorrect: false},
  ],
  [
    {value:'Thấy ghét', isCorrect: false},
    {value:'Dễ thương', isCorrect: true},
    {value:'Khó tính', isCorrect: false},
    {value:'Ăn gian', isCorrect: false},
  ],
  [
    {value:' ', isCorrect: true},
    {value:' ', isCorrect: false},
    {value:' ', isCorrect: true},
    {value:' ', isCorrect: false},
  ],
];
